import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers/chakraprovider";
import FramerAminateLayout from "@/providers/FramerAminateLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Framer Motion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <FramerAminateLayout>
            {children}
          </FramerAminateLayout>
        </Providers>
      </body>
    </html>
  );
}
